//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class images
    {
        public int id { get; set; }
        public string url { get; set; }
        public Nullable<int> im_product_id { get; set; }
        public string im_name { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
