//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public Nullable<int> or_transaction_id { get; set; }
        public Nullable<int> or_product_id { get; set; }
        public Nullable<int> or_user_id { get; set; }
        public Nullable<byte> or_quantiy { get; set; }
        public Nullable<int> or_final_price { get; set; }
        public Nullable<int> or_price_old { get; set; }
        public Nullable<byte> or_sale { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual product product { get; set; }
        public virtual transaction transaction { get; set; }
    }
}
