//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.orders = new HashSet<orders>();
        }
    
        public int id { get; set; }
        public Nullable<int> pro_author_id { get; set; }
        public string pro_name { get; set; }
        public Nullable<int> pro_category_id { get; set; }
        public Nullable<int> pro_price { get; set; }
        public Nullable<int> pro_brand_id { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<int> pro_quantity { get; set; }
        public string pro_description { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<double> final_price { get; set; }
        public string pro_avatar { get; set; }
        public Nullable<int> pro_active { get; set; }
        public Nullable<int> size_L { get; set; }
        public Nullable<int> size_M { get; set; }
        public Nullable<int> size_S { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
    }
}
