//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.orders = new HashSet<order>();
        }
    
        public int id { get; set; }
        public string pro_name { get; set; }
        public Nullable<int> pro_category_id { get; set; }
        public Nullable<decimal> pro_price { get; set; }
        public Nullable<int> pro_brand_id { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<byte> pro_quantity { get; set; }
        public string pro_description { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string pro_size { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string image { get; set; }
        public Nullable<double> final_price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
        public virtual size size { get; set; }
    }
}
