//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transactions()
        {
            this.orders = new HashSet<orders>();
        }
    
        public int id { get; set; }
        public Nullable<int> tr_user_id { get; set; }
        public Nullable<int> tr_total { get; set; }
        public string tr_note { get; set; }
        public string tr_address { get; set; }
        public string tr_phone { get; set; }
        public Nullable<byte> tr_status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
    }
}
